/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdatkezelesRouteImport } from './routes/adatkezeles'
import { Route as ArakRouteImport } from './routes/arak'
import { Route as AszfRouteImport } from './routes/aszf'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as ReferenciakRouteImport } from './routes/referenciak'
import { Route as RolunkRouteImport } from './routes/rolunk'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SutikRouteImport } from './routes/sutik'
import { Route as SzolgaltatasokRouteImport } from './routes/szolgaltatasok'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdatkezelesRoute = AdatkezelesRouteImport.update({
  id: '/adatkezeles',
  path: '/adatkezeles',
  getParentRoute: () => rootRouteImport,
} as any)
const ArakRoute = ArakRouteImport.update({
  id: '/arak',
  path: '/arak',
  getParentRoute: () => rootRouteImport,
} as any)
const AszfRoute = AszfRouteImport.update({
  id: '/aszf',
  path: '/aszf',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenciakRoute = ReferenciakRouteImport.update({
  id: '/referenciak',
  path: '/referenciak',
  getParentRoute: () => rootRouteImport,
} as any)
const RolunkRoute = RolunkRouteImport.update({
  id: '/rolunk',
  path: '/rolunk',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SutikRoute = SutikRouteImport.update({
  id: '/sutik',
  path: '/sutik',
  getParentRoute: () => rootRouteImport,
} as any)
const SzolgaltatasokRoute = SzolgaltatasokRouteImport.update({
  id: '/szolgaltatasok',
  path: '/szolgaltatasok',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adatkezeles': typeof AdatkezelesRoute
  '/arak': typeof ArakRoute
  '/aszf': typeof AszfRoute
  '/blog': typeof BlogRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/referenciak': typeof ReferenciakRoute
  '/rolunk': typeof RolunkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sutik': typeof SutikRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adatkezeles': typeof AdatkezelesRoute
  '/arak': typeof ArakRoute
  '/aszf': typeof AszfRoute
  '/blog': typeof BlogRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/referenciak': typeof ReferenciakRoute
  '/rolunk': typeof RolunkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sutik': typeof SutikRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adatkezeles': typeof AdatkezelesRoute
  '/arak': typeof ArakRoute
  '/aszf': typeof AszfRoute
  '/blog': typeof BlogRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/referenciak': typeof ReferenciakRoute
  '/rolunk': typeof RolunkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sutik': typeof SutikRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adatkezeles'
    | '/arak'
    | '/aszf'
    | '/blog'
    | '/kapcsolat'
    | '/referenciak'
    | '/rolunk'
    | '/sitemap.xml'
    | '/sutik'
    | '/szolgaltatasok'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adatkezeles'
    | '/arak'
    | '/aszf'
    | '/blog'
    | '/kapcsolat'
    | '/referenciak'
    | '/rolunk'
    | '/sitemap.xml'
    | '/sutik'
    | '/szolgaltatasok'
  id:
    | '__root__'
    | '/'
    | '/adatkezeles'
    | '/arak'
    | '/aszf'
    | '/blog'
    | '/kapcsolat'
    | '/referenciak'
    | '/rolunk'
    | '/sitemap.xml'
    | '/sutik'
    | '/szolgaltatasok'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdatkezelesRoute: typeof AdatkezelesRoute
  ArakRoute: typeof ArakRoute
  AszfRoute: typeof AszfRoute
  BlogRoute: typeof BlogRoute
  KapcsolatRoute: typeof KapcsolatRoute
  ReferenciakRoute: typeof ReferenciakRoute
  RolunkRoute: typeof RolunkRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SutikRoute: typeof SutikRoute
  SzolgaltatasokRoute: typeof SzolgaltatasokRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adatkezeles': {
      id: '/adatkezeles'
      path: '/adatkezeles'
      fullPath: '/adatkezeles'
      preLoaderRoute: typeof AdatkezelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arak': {
      id: '/arak'
      path: '/arak'
      fullPath: '/arak'
      preLoaderRoute: typeof ArakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aszf': {
      id: '/aszf'
      path: '/aszf'
      fullPath: '/aszf'
      preLoaderRoute: typeof AszfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenciak': {
      id: '/referenciak'
      path: '/referenciak'
      fullPath: '/referenciak'
      preLoaderRoute: typeof ReferenciakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolunk': {
      id: '/rolunk'
      path: '/rolunk'
      fullPath: '/rolunk'
      preLoaderRoute: typeof RolunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sutik': {
      id: '/sutik'
      path: '/sutik'
      fullPath: '/sutik'
      preLoaderRoute: typeof SutikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szolgaltatasok': {
      id: '/szolgaltatasok'
      path: '/szolgaltatasok'
      fullPath: '/szolgaltatasok'
      preLoaderRoute: typeof SzolgaltatasokRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdatkezelesRoute: AdatkezelesRoute,
  ArakRoute: ArakRoute,
  AszfRoute: AszfRoute,
  BlogRoute: BlogRoute,
  KapcsolatRoute: KapcsolatRoute,
  ReferenciakRoute: ReferenciakRoute,
  RolunkRoute: RolunkRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SutikRoute: SutikRoute,
  SzolgaltatasokRoute: SzolgaltatasokRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
